name: engage
description: What's your plan?

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  keyboard_visibility: ^0.5.6

  intl: ^0.16.1

  auro_avatar: ^0.1.1

  shimmer: ^1.0.0
  
  random_string: ^2.1.0

  flappy_search_bar: ^1.7.2

  badges: ^1.1.4

  transparent_image: ^1.0.0

  intro_slider: ^2.3.3

  carousel_slider: ^1.3.0

  titled_navigation_bar: ^3.5.0

  provider: ^4.3.2+2

  bloc: ^6.1.0

  flutter_bloc: ^6.1.1

  equatable: ^1.2.3
  
  form_validator: ^0.1.5

  flutter_login: ^1.0.14

  flutter_session: ^0.1.1

  rflutter_alert: ^1.1.0
  
  riverpod: ^0.12.1

  dio: ^3.0.10

  dio_retry: ^0.1.9-beta

  http_parser: ^3.1.4

  shared_preferences: ^0.5.12+4

  #Firebase
  #firebase_core: ^0.4.0+1

  # Add the dependency for the FlutterFire plugin for Google Analytics
  #firebase_analytics: ^6.1.0

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  #firebase_auth: ^0.18.1+2
  #cloud_firestore: ^0.14.2


  # Flutter
  flutter_localizations:
      sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  flutter_launcher_icons: ^0.8.1

  flutter_screenutil: ^0.5.3
  
  fluttertoast: ^7.1.1
  
  flutter_form_builder: ^3.14.1

flutter_icons:
  image_path: "assets/images/Asset 2@2x.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf

    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen/Oxygen-Light.ttf
        - asset: assets/fonts/Oxygen/Oxygen-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
